import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-bright": "var(--color-surface-bright)",
        background: "var(--color-background)",

        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",

        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-surface": "var(--color-inverse-surface)",

        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",

        error: "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        success: "var(--color-success)",
        "success-soft": "var(--color-success-soft)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        info: "var(--color-info)",
        "info-soft": "var(--color-info-soft)",
        muted: "var(--color-muted)",
        "accent-violet": "var(--color-accent-violet)",
        "accent-indigo": "var(--color-accent-indigo)",
        "accent-plum": "var(--color-accent-plum)",
        "accent-cobalt": "var(--color-accent-cobalt)",
        "accent-orange": "var(--color-accent-orange)",
        "accent-orange-strong": "var(--color-accent-orange-strong)",
        "accent-google-blue": "var(--color-accent-google-blue)",
        "accent-google-green": "var(--color-accent-google-green)",
        "accent-google-yellow": "var(--color-accent-google-yellow)",
        "accent-google-red": "var(--color-accent-google-red)",
      },
      fontFamily: {
        headline: "var(--font-primary)",
        body: "var(--font-primary)",
        label: "var(--font-primary)",
        mono: "var(--font-mono)",
        "mono-data": "var(--font-mono)",
      },
      fontSize: {
        "3xs": ["0.5625rem", { lineHeight: "0.75rem" }],
        "2xs": ["0.625rem", { lineHeight: "0.75rem" }],
        tiny: ["0.6875rem", { lineHeight: "0.875rem" }],
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
        "10xl": ["6.25rem", { lineHeight: "1" }],
        metric: ["2.15rem", { lineHeight: "1" }],
      },
      letterSpacing: {
        "tight-sm": "-0.03em",
        "tight-md": "-0.04em",
        "tight-xl": "-0.08em",
        "label-xs": "0.14em",
        "label-sm": "0.16em",
        "label-md": "0.18em",
        "label-lg": "0.2em",
        "label-xl": "0.22em",
        "label-2xl": "0.24em",
        "label-3xl": "0.26em",
        "label-4xl": "0.28em",
        "label-5xl": "0.3em",
      },
      spacing: {
        "11.5": "2.875rem",
        "18": "4.5rem",
        "90": "22.5rem",
        "88": "22rem",
        "105": "26.25rem",
        "110": "27.5rem",
        "112": "28rem",
        "112.5": "28.125rem",
        "120": "30rem",
        "128": "32rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        auth: "1.25rem",
        feature: "1.35rem",
        metric: "1.4rem",
        tile: "1.6rem",
        panel: "1.75rem",
        hero: "2rem",
      },
      boxShadow: {
        nocturnal: "var(--shadow-nocturnal)",
        panel: "var(--shadow-panel)",
        glow: "var(--shadow-glow)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-in": "slideIn 0.3s ease-out",
        "float-slow": "floatSlow 8s ease-in-out infinite",
        "pulse-soft": "pulseSoft 3s ease-in-out infinite",
        shimmer: "shimmer 2.2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        floatSlow: {
          "0%, 100%": { transform: "translate3d(0, 0, 0)" },
          "50%": { transform: "translate3d(0, -10px, 0)" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "0.8" },
          "50%": { opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
